### ISSUE TITLE
Use "category" to group commands for easier discovery

### ISSUE THREAD

**Issue by akaroml** [OpenLiberty/liberty-dev-vscode-ext#17]
All the commands in this extension do not have a category specified. In this case, it's really hard for users to discover those commands. Check out how it looks like in the command palette:
<img width="724" alt="Screen Shot 2019-11-29 at 11 24 29 AM" src="https://user-images.githubusercontent.com/16755094/69841656-06b55780-129b-11ea-9434-cbe7e025d5e6.png">
It's really hard to tell those two commands are related to your product and users could be very easily confused.

Please check out this example. This extension uses the "Java" category to group all its command.
https://github.com/redhat-developer/vscode-java/blob/master/package.json#L404
And it looks like this:
![image](https://user-images.githubusercontent.com/16755094/69841725-53992e00-129b-11ea-820e-b05b65125a82.png)

So here to suggest that you guys add category field to all your commands in here:
https://github.com/OpenLiberty/liberty-dev-vscode-ext/blob/master/package.json#L45

**Comment by yeekangc** [comment]
Thank you, @akaroml.  We will take a look at this as soon as possible.

**Comment by kathrynkodama** [comment]
Fixed with #18 and #19
