### ISSUE TITLE
Killing the devmode terminal prevents you from re-launching devmode.

### ISSUE THREAD

**Issue by rzgry** [OpenLiberty/liberty-dev-vscode-ext#32]
#### Steps to reproduce:
1. Start devmode using the liberty dev dashboard.
2. Kill the terminal either with:
  * The kill terminal button <img width="165" alt="Screen Shot 2020-01-20 at 1 10 28 PM" src="https://user-images.githubusercontent.com/16768710/72749011-d72e1780-3b86-11ea-93ba-ccbbdca4759e.png">
  * Killing the terminal with the exit command. (Can be triggered by accidently running `Stop` from the liberty dev dashboard twice) 
3. Try to start devmode again from the liberty-dev dashboard.

#### Expected output: 
Starts dev-mode 

#### Actual output:
Nothing happens

**Comment by kathrynkodama** [comment]
Fixed with #35
