### ISSUE TITLE
Improve SEO in VSCode marketplace.

### ISSUE THREAD

**Issue by rzgry** [OpenLiberty/liberty-dev-vscode-ext#36]
Ex. Searching for `OpenLiberty` returns no results https://marketplace.visualstudio.com/search?term=openliberty&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by rzgry** [comment]
You can specify `keywords` in the extension manifest which are using during search (https://code.visualstudio.com/api/references/extension-manifest#combining-extension-contributions) but it only allows up to 5. So we will want to optimize these.

**Comment by kathrynkodama** [comment]
Should we add `MicroProfile` if this is planned to be a part of the MicroProfile Extension Pack eventually?   Then we have `Java`, `Open Liberty`, `Maven`, `Gradle`, and `MicroProfile`.
