### ISSUE TITLE
Unable to launch dev mode if liberty-maven-plugin is not defined in project plugin section

### ISSUE THREAD

**Issue by patricktiu** [OpenLiberty/liberty-dev-vscode-ext#4]
Since the `start` command for project under the `LIBERTY DEV DASHBOARD` is calling `mvn liberty:dev`, it has an assumption that the liberty-maven-plugin is defined in the project.

**Comment by kathrynkodama** [comment]
Modifying the start and custom commands to use: `mvn io.openliberty.tools:liberty-maven-plugin:dev...`

**Comment by kathrynkodama** [comment]
fixed with #2
