### ISSUE TITLE
Change Boost groupId to org.microshed.boost

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/liberty-dev-vscode-ext#6]
Boost Maven plugin has groupId `org.microshed.boost`.  The VS Code extension (and the readme) should refer to this groupId when checking for dev projects.

e.g.
```
<groupId>org.microshed.boost</groupId>
<artifactId>boost-maven-plugin</artifactId>
```

**Comment by kathrynkodama** [comment]
fixed with #7
